slogan: ""

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"
  # - title: RSS
  #   url: atom.xml
  #   intro: "Subscribe me."
  #   icon: "fa fa-user"

links:
  - title: GitHub - TouHikari
    url: https://github.com/touhikari
    intro: ""
    icon: false

  - title: bilibili | 哔哩哔哩 - HvnZ_Null
    url: https://space.bilibili.com/123365221

  - title: NetEase Music | 网易云音乐 - HvnZ_Null
    url: https://music.163.com/#/user/home?id=436110203

  - title: hexo-theme-bithack | 本站使用的主题
    url: https://github.com/Ares-X/hexo-theme-freemind.bithack
    intro: ""
    icon: false


widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: atom.xml
fancybox: true
favicon: favicon.png
#duoshuo_shortname: 


# Analytics
google_analytics:
  enable: false
  siteid: 


# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

#valine
valine: 
  enable: false
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: ""
  visitor: false
  avatar: 'monsterid'
  requiredFields: ['nick','mail']
  pageView: false
  
#waline
waline:
  enable: false
  serverURL: ''
  pageview: false
  lang: zh-CN
  dark: true
  requiredMeta: ['nick', 'mail']
  locale:
    placeholder: 'Comment with Email address will get notification when replied'

gitalk:
  enable: false
  clientID: ''
  clientSecret: ''
  repo: ''
  owner: ''
  admin: ['']
  id: location.pathname
  distractionFreeMode: true

# Math config
math:
  enable: true     # Enable math rendering (load scripts)
  service: KaTeX   # Choose rendering service: KaTeX or MathJax

  katex:
    inlineMath: [['$', '$'], ['\\(', '\\)']]   # Delimiters for inline math
    displayMath: [['$$', '$$'], ['\\[', '\\]']] # Delimiters for block math
    options:
       throwOnError: false # Don't throw errors on invalid math
       # ignoredClasses: ["no-math", "code", "highlight"] # Optional: skip rendering within these classes (useful for code blocks)
